apiVersion: v1
kind: Service
metadata:
  name: ordering-api-service
spec:
  type: ClusterIP
  selector:
    app: ordering-api
  ports:
    - protocol: TCP
      port: 5224
      targetPort: 5224
      name: http
