apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-configmap
  labels:
    app: postgres
data:
  01-init.sql: |
    CREATE DATABASE identitydb;
    CREATE DATABASE catalogdb;
    CREATE DATABASE orderingdb;

    \connect identitydb
    CREATE EXTENSION IF NOT EXISTS vector;

    \connect catalogdb
    CREATE EXTENSION IF NOT EXISTS vector;

    \connect orderingdb
    CREATE EXTENSION IF NOT EXISTS vector;
