
env.IMAGE_NAME = "ahmniab/eshop-catalog-api"
// VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()

env.DOCKERFILE_TEST = "Dockerfile.test"
env.DOCKERFILE_APP = "Dockerfile"
env.CONTEXT_PATH = "src/microservices/eShop.Catalog.API"


stage('Test Catalog API') {
    sh "docker build -f ${env.CONTEXT_PATH}/${env.DOCKERFILE_TEST} ${env.CONTEXT_PATH}"
}

stage('Build Catalog API Image') {
    sh """
        docker build \
        -t ${env.IMAGE_NAME}:${env.VERSION} \
        -f ${env.CONTEXT_PATH}/${env.DOCKERFILE_APP} \
        ${env.CONTEXT_PATH}
        """
}

stage('Push Catalog API Image to DockerHub') {
    sh """
        docker push ${env.IMAGE_NAME}:${env.VERSION}
    """
}

