
env.IMAGE_NAME = "ahmniab/eshop-basket-api"
// VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()



stage('Run Tests for Basket API') {
    sh """
    docker run --rm \
        -v "${WORKSPACE}/src/microservices/eShop.Basket.API:/app:z" \
        -w /app \
        -e DOTNET_CLI_HOME=/app/.dotnet-temp \
        mcr.microsoft.com/dotnet/sdk:10.0 \
        dotnet test eShop.Basket.API.sln
    """

}

stage('Build and Push Basket API Image') {
    sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} src/microservices/eShop.Basket.API"
    sh "docker push ${env.IMAGE_NAME}:${env.VERSION}"
}
