
env.IMAGE_NAME = "ahmniab/eshop-webapp"
// VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()


stage('Run Tests') {
    sh """
    docker run --rm \
        -v "${WORKSPACE}/src/microservices/eShop.WebApp:/app:z" \
        -w /app \
        -e DOTNET_CLI_HOME=/app/.dotnet-temp \
        mcr.microsoft.com/dotnet/sdk:10.0 \
        dotnet test eShop.WebApp.sln
    """

}

stage('Build and Push Web App Image') {
    sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} src/microservices/eShop.WebApp"
    sh "docker push ${env.IMAGE_NAME}:${env.VERSION}"
}