apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-api-configmap
  labels:
    component: shared-infrastructure
data:
  Identity__Url: "http://18.206.250.232:30223"
  Identity__MetadataAddress: "http://identity-api-service:5223"
  Identity__Audience: "basket"
  ASPNETCORE_ENVIRONMENT: "Production"
