
env.IMAGE_NAME = "ahmniab/eshop-order-processor"
// VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()

stage('Run Tests for Order Processor') {
    sh """
    docker run --rm \
        -v "${WORKSPACE}/src/microservices/eShop.OrderProcessor:/app:z" \
        -w /app \
        -e DOTNET_CLI_HOME=/app/.dotnet-temp \
        mcr.microsoft.com/dotnet/sdk:10.0 \
        dotnet test eShop.OrderProcessor.sln
    """
}

stage('Build and Push Order Processor Image') {
    sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} src/microservices/eShop.OrderProcessor"
    sh "docker push ${env.IMAGE_NAME}:${env.VERSION}"
}